= Guide for launching the provider on your device

. Download the contents of the main branch to your device

. Build the provider code using the command
* Linux
[source, go]
go build -o terraform-provider-virtualbox
* Windows
[source, go]
go build -o terraform-provider-virtualbox.exe

. In order to use the provider, we need to create the below directory structure inside the plugins directory 
* Linux
[source, bash]
~/.terraform.d/plugins/${host_name}/${namespace}/${type}/${version}/${target}

* Windows
[source, shell]
%APPDATA%\terraform.d\plugins\${host_name}\${namespace}\${type}\${version}\${target}

* Where:
** host_name -> somehostname.com
** namespace -> provider name space
** type -> provider type
** version -> semantic versioning of the provider
** target -> target operating system

* As a first step, we need to the create the directory
** Linux
[source, bash]
mkdir -p ~/.terraform.d/plugins/terraform-virtualbox.local/virtualboxprovider/virtualbox/1.0.0/linux_amd64

** Windows
[source, shell]
mkdir Path_to_the_AppData_folder\AppData\Roaming\terraform.d\plugins\terraform-virtualbox.local\virtualboxprovider\virtualbox\1.0.0\windows_amd64

* Then, copy the terraform-provider-virtualbox to the created directory
** Linux
[source, bash]
cp terraform-provider-virtualbox ~/.terraform.d/plugins/terraform-virtualbox.local/virtualboxprovider/virtualbox/1.0.0/linux_amd64

** Windows
[source, shell]
cp terraform-provider-virtualbox.exe Path_to_the_AppData_folder\AppData\Roaming\terraform.d\plugins\terraform-virtualbox.local\virtualboxprovider\virtualbox\1.0.0\windows_amd64

. Go to the config folder
[source, bash]
cd config

. Use the commands 
* Terraform init
* Terraform plan
* Terraform apply
* Terraform destroy



